name: Python validate

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install freezegun pytest flask flask_cors yfinance scipy mypy ruff
    - name: Ruff lint
      run: |
        ruff check .
    - name: mypy type check
      run: |
        mypy --install-types --non-interactive .
    - name: Test with pytest
      run: pytest
